<?php

declare(strict_types=1);

use GuzzleHttp\Client as GuzzleClient;
use GuzzleHttp\Handler\CurlHandler;
use Http\Factory\Guzzle\RequestFactory;
use Http\Factory\Guzzle\StreamFactory;
use setasign\SetaPDF\Signer\Module\GlobalTrustTrust2Go\Client;
use setasign\SetaPDF\Signer\Module\GlobalTrustTrust2Go\Module;
use setasign\SetaPDF2\Core\Document;
use setasign\SetaPDF2\Core\Reader\FileReader;
use setasign\SetaPDF2\Core\Writer\FileWriter;
use setasign\SetaPDF2\Signer\Digest;
use setasign\SetaPDF2\Signer\Signer;

require_once __DIR__ . '/../vendor/autoload.php';

if (!file_exists(__DIR__ . '/settings.php')) {
    throw new RuntimeException('Missing settings.php!');
}
$settings = require __DIR__ . '/settings.php';

$file = __DIR__ . '/assets/tektown/Laboratory-Report.pdf';
$certificateSerialNumber = $settings['certificateSerialNumber'];
// A requestID generated by the client to identify this signature operation (6 alphanumeric characters)
$requestId = '123456';

$httpClient = new GuzzleClient([
    'handler' => new CurlHandler(),
    // note: guzzle requires this parameter to fully support PSR-18
    'http_errors' => false,
    // timeout by api after ~300 seconds
    'timeout' => 360,
]);

$client = new Client(
    $httpClient,
    new RequestFactory(),
    new StreamFactory(),
    $settings['apiUrl'],
    $settings['username'],
    $settings['activationPin']
);

$module = new Module($client, $requestId, $certificateSerialNumber);
$module->setDigest(Digest::SHA_512);

$reader = new FileReader($file);
$writer = new FileWriter(__DIR__ . '/output/demo.pdf');
// let's get the document
$document = Document::load($reader, $writer);

// now let's create a signer instance
$signer = new Signer($document);
$signer->setAllowSignatureContentLengthChange(false);
//$signer->setSignatureContentLength(36000);

//// set some signature properties
$signer->setReason('Testing TRUST2GO');

$field = $signer->getSignatureField();
$signer->setSignatureFieldName($field->getQualifiedName());

$signer->sign($module);
