<?php

declare(strict_types=1);

namespace setasign\SetaPDF\Signer\Module\GlobalTrustTrust2Go;

use Exception;
use InvalidArgumentException;
use Psr\Http\Client\ClientExceptionInterface;
use setasign\SetaPDF2\Core\Reader\FilePath;
use setasign\SetaPDF2\Signer\Asn1\Exception as Asn1Exception;
use setasign\SetaPDF2\Signer\Digest;
use setasign\SetaPDF2\Signer\Exception as SignerException;
use setasign\SetaPDF2\Signer\Signature\Module\DictionaryInterface;
use setasign\SetaPDF2\Signer\Signature\Module\DocumentInterface;
use setasign\SetaPDF2\Signer\Signature\Module\ModuleInterface;
use setasign\SetaPDF2\Signer\Signature\Module\PadesProxyTrait;

class Module implements
    ModuleInterface,
    DictionaryInterface,
    DocumentInterface
{
    use PadesProxyTrait;

    protected Client $client;
    protected string $requestId;
    protected string $certificateSerialNumber;

    /**
     * @param Client $client
     * @param string $requestId A requestID generated by the client to identify this signature operation (6 alphanumeric characters)
     * @param string $certificateSerialNumber
     */
    public function __construct(Client $client, string $requestId, string $certificateSerialNumber)
    {
        $this->client = $client;
        $this->requestId = $requestId;
        $this->certificateSerialNumber = $certificateSerialNumber;
    }

    public function setDigest(string $digest): void
    {
        if (!\in_array(
            $digest,
            [
                Digest::SHA_256,
                Digest::SHA_384,
                Digest::SHA_512
            ],
            true
        )) {
            throw new InvalidArgumentException('Invalid digest.');
        }
        $this->_getPadesModule()->setDigest($digest);
    }

    /**
     * @param FilePath $tmpPath
     * @return string
     * @throws ClientExceptionInterface
     * @throws Asn1Exception
     * @throws SignerException
     * @throws Exception
     */
    public function createSignature(FilePath $tmpPath): string
    {
        if ($this->getCertificate() === null) {
            $certificate = $this->client->getCertificateBySerialNumber($this->certificateSerialNumber);
            $this->setCertificate($certificate['certificate']);
            $this->setExtraCertificates($certificate['chain']);
        }

        $padesModule = $this->_getPadesModule();
        $digest = $padesModule->getDigest();
        // get the hash data from the module
        $hash = \base64_encode(\hash($digest, $padesModule->getDataToSign($tmpPath), true));
        $padesModule->setSignatureValue(
            $this->client->sign($this->certificateSerialNumber, $this->requestId, $digest, $hash)
        );

        return (string) $padesModule->getCms();
    }
}
